SELECT *
FROM Student
WHERE COURSE_CODE = '305';

UPDATE Student
SET COURSE_CODE = '304'
WHERE STU_NUM = '07';

DELETE FROM Student
WHERE STU_SNAME = 'Lannister' AND STU_FNAME = 'Jamie' AND STU_STARTDATE = 2012-09-05 AND COURSE_CODE = '101' AND PROJ_NUM = 2;

UPDATE Student
SET PROJ_NUM = 14
WHERE STU_STARTDATE < '2016-01-01' AND COURSE_CODE = '201';

SELECT *
FROM Student;

DROP TABLE Student;
